In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


from subprocess import check_output
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
meta_data = pd.read_csv("C:\\Users\\Administrator\\Desktop\\Dataming Project\\Fraud data.csv")
del meta_data['nameDest']
del meta_data['nameOrig']
del meta_data['type']
del meta_data['isFlaggedFraud']
len(meta_data)

6362620

In [3]:
Cols = meta_data[['step','amount','oldbalanceOrg','newbalanceOrig','oldbalanceDest','newbalanceDest']]
y = meta_data['isFraud']
X = Cols

In [4]:


from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
rfc = RandomForestClassifier() #using default values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42) #use this random state to match my results only
#training our model
model = rfc.fit(X_train,y_train)
#predicting our labels
predictions = model.predict(X_test)

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00   1906351
          1       0.95      0.71      0.81      2435

avg / total       1.00      1.00      1.00   1908786

[[1906257      94]
 [    709    1726]]


0.99957931376277909

In [6]:


print ("Random Forest Accuracy", accuracy_score(y_test,predictions))

Random Forest Accuracy 0.999579313763


In [7]:
from sklearn import linear_model
logitic = linear_model.LogisticRegression()
model = logitic.fit(X_train,y_train)
predictions = model.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))
accuracy_score(y_test,predictions)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00   1906351
          1       0.32      0.73      0.44      2435

avg / total       1.00      1.00      1.00   1908786

[[1902492    3859]
 [    660    1775]]


0.9976325266425885

In [8]:
print ("Logistic Regression Accuracy", accuracy_score(y_test,predictions))

Logistic Regression Accuracy 0.997632526643


In [9]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
model = gnb.fit(X_train,y_train)
predictions = model.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))
accuracy_score(y_test,predictions)


             precision    recall  f1-score   support

          0       1.00      0.99      1.00   1906351
          1       0.03      0.16      0.05      2435

avg / total       1.00      0.99      0.99   1908786

[[1893838   12513]
 [   2043     392]]


0.99237421062392539

In [10]:
print ("Navie bayes Accuracy", accuracy_score(y_test,predictions))

Navie bayes Accuracy 0.992374210624


In [11]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA()
model = lda.fit(X_train,y_train)
predictions = model.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))
accuracy_score(y_test,predictions)


             precision    recall  f1-score   support

          0       1.00      1.00      1.00   1906351
          1       0.72      0.37      0.49      2435

avg / total       1.00      1.00      1.00   1908786

[[1906003     348]
 [   1534     901]]


0.99901403300317582

In [12]:
print ("LDA Accuracy", accuracy_score(y_test,predictions))

LDA Accuracy 0.999014033003


In [13]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
qda = QDA()
model = qda.fit(X_train,y_train)
predictions = model.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))
accuracy_score(y_test,predictions)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00   1906351
          1       0.18      0.54      0.27      2435

avg / total       1.00      1.00      1.00   1908786

[[1900251    6100]
 [   1130    1305]]


0.99621225218542042

In [14]:
print ("QDA Accuracy", accuracy_score(y_test,predictions))

QDA Accuracy 0.996212252185
